### ISSUE TITLE
[Feat] ERD 기반 엔티티 생성 

### ISSUE THREAD

**Issue by woosung1223** [Princess-in-silvertown/toyou-server#5]
## 🚀 Highlights
- 기본 엔티티를 생성합니다.

## 📌 Tasks
- JPA 엔티티 생성하기

## 📝 Details
- [x] H2 기반으로 연동이 되도록 기본 뼈대만 구현합니다.
- [x] `lastModifedDate`, `createdDate`를 고정 필드로 추가합니다.

## 📚 Remarks

-

**Comment by loveysuby** [comment]
Merged with revisiion about `Member` has privilege to create `Rolling_Paper`. [3fb002e](https://github.com/Princess-i-silvertown/toyou-server/commit/3fb002edafc092e7e588f30f4f65aa1116ef75c2)
